buildscript {
  ext.kotlin_version = '1.9.22'
  repositories {
    gradlePluginPortal()
    mavenCentral()
  }
  dependencies {
    // 使用jpackage只有在JDK版本为14或更高时才有效。
    // 你的JAVA_HOME环境变量可能也需要指向版本为14或更高的JDK。
    if (JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_14)) {
      classpath "org.beryx:badass-runtime-plugin:1.12.7"
    }
  }
}

apply plugin: "org.jetbrains.kotlin.plugin.compose"
apply plugin: "org.jetbrains.compose"
apply plugin: 'org.jetbrains.kotlin.jvm'
apply plugin: 'kotlin'

kotlin {
  jvmToolchain(21)
}

if (JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_14)) {
//  apply plugin: 'org.beryx.runtime'
} else {
//  apply plugin: 'application'
}

sourceSets.main.resources.srcDirs += [
  // rootProject.file('game0001/assets').path
  '../../assets',
  '../assets'
]
//mainClassName = 'pama1234.gdx.game.app.lwjgl3.Launcher'
eclipse.project.name = appName + '0001-lwjgl3'

dependencies {
  implementation "$gdxModule:gdx-backend-lwjgl3:$gdxVersion"
  // implementation "$gdxCustomModule:gdx-bullet-platform:$gdxCustomVersion:natives-desktop"
  implementation "$gdxModule:gdx-platform:$gdxVersion:natives-desktop"

  implementation "$pama1234RepoLocation:lwjgl-framework:$pama1234PublishVersion"
  implementation project(':game0001:game0001-core')

  // implementation "com.mazatech.amanithsvg:amanithsvg-gdx:$amanithsvgVersion:natives-desktop"

  // Compose for desktop
  implementation("org.jetbrains.compose.desktop:desktop:1.4.0")
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version" // 使用适合的Compose版本
}

compose.desktop {
  application {
    mainClass = "pama1234.gdx.game.app.lwjgl3.Launcher" // 你应用程序的入口类
  }
}

def os = System.properties['os.name'].toLowerCase()

jar {
  // 将生成的.jar文件的名称设置为游戏或应用程序的名称。
  archiveBaseName.set(eclipse.project.name)
  // 使用'lib'而不是默认的'libs'似乎是jpackageimage所需要的。
  destinationDirectory = file("$project.buildDir/lib")
  // 从Gradle 7.0开始，duplicatesStrategy变得重要；这个设置是有效的。
  duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
  dependsOn configurations.runtimeClasspath
  from {
    configurations.runtimeClasspath.collect {
      it.isDirectory() ? it : zipTree(it)
    }
  }
  // 这些"exclude"行删除了输出JAR中一些不必要的重复文件。
  exclude('META-INF/INDEX.LIST', 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA')
  dependencies {
    exclude('META-INF/INDEX.LIST', 'META-INF/maven/**')
  }
  // 设置manifest使JAR可运行。
  manifest {
    attributes 'Main-Class': 'pama1234.gdx.game.app.lwjgl3.Launcher'
  }
  // 这最后一步可能有助于在一些需要额外指令来制作可运行JAR的操作系统上。
  doLast {
    file(archiveFile).setExecutable(true, false)
  }
}

// 等同于jar任务；这里是为了与gdx-setup兼容。
task dist(dependsOn: [jar]) { }

// 添加以下任务依赖关系来解决报错
tasks.named('processResources') {
  dependsOn 'prepareComposeResourcesTaskForMain'
  dependsOn 'copyNonXmlValueResourcesForMain'
  dependsOn 'convertXmlValueResourcesForMain'
}
