/****************************************************************************
 ** Copyright (c) 2013-2018 Mazatech S.r.l. All rights reserved.
 ** 
 ** Redistribution and use in source and binary forms, with or without modification, are
 * permitted (subject to the limitations in the disclaimer below) provided that the following
 * conditions are met:
 ** 
 ** - Redistributions of source code must retain the above copyright notice, this list of
 * conditions and the following disclaimer.
 ** 
 ** - Redistributions in binary form must reproduce the above copyright notice, this list of
 * conditions and the following disclaimer in the documentation and/or other materials provided
 * with the distribution.
 ** 
 ** - Neither the name of Mazatech S.r.l. nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific prior written
 * permission.
 ** 
 ** NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS
 * SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER
 ** OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 ** OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 ** 
 ** For any information, please contact info@mazatech.com
 ** 
 ****************************************************************************/
package com.mazatech.svgt;

public enum SVGTError{
    None(AmanithSVG.SVGT_NO_ERROR),
    Uninitialized(AmanithSVG.SVGT_NOT_INITIALIZED_ERROR),
    BadHandle(AmanithSVG.SVGT_BAD_HANDLE_ERROR),
    IllegalArgument(AmanithSVG.SVGT_ILLEGAL_ARGUMENT_ERROR),
    OutOfMemory(AmanithSVG.SVGT_OUT_OF_MEMORY_ERROR),
    XMLParser(AmanithSVG.SVGT_PARSER_ERROR),
    // returned when the library detects that outermost element is not an <svg> element or there is a circular dependency (usually generated by <use> elements)
    InvalidSVG(AmanithSVG.SVGT_INVALID_SVG_ERROR),
    StillPacking(AmanithSVG.SVGT_STILL_PACKING_ERROR),
    NotPacking(AmanithSVG.SVGT_NOT_PACKING_ERROR),
    Unknown(AmanithSVG.SVGT_UNKNOWN_ERROR);
    SVGTError(int svgtEnum) {
        _svgtEnum=svgtEnum;
    }
    public int getValue() {
        return _svgtEnum;
    }
    public static SVGTError fromValue(int svgtEnum) {
        return _allValues[svgtEnum];
    }
    private final int _svgtEnum;
    private static SVGTError[] _allValues=values();
}
