apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: "org.jetbrains.kotlin.plugin.compose"
apply plugin: 'org.jetbrains.compose'

configurations {
  all {
    // exclude group: "$pama1234RepoLocation", module: "server-framework"
    // exclude group: "javax.vecmath", module: "*"
    // exclude group: "com.esotericsoftware", module: "*"
    // exclude group: "com.google.code.gson", module: "*"
    // exclude group: "org.yaml", module: "*"
    // exclude group: "io.netty", module: "*"
  }
}

android {
  namespace 'pama1234'
//  compileSdkVersion project.properties.compileSdkVersion.toInteger()
  signingConfigs {
    release {
      // storeFile file('sign.jks')
      // storePassword ''
      // keyAlias 'xxx'
      // keyPassword ''
    }
  }
  sourceSets {
    main {
      manifest.srcFile 'AndroidManifest.xml'
      java.srcDirs = ['src/main/java']
      aidl.srcDirs = ['src/main/java']
      renderscript.srcDirs = ['src/main/java']
      res.srcDirs = ['res']
      assets.srcDirs = ['../../assets' , '../assets']
      jniLibs.srcDirs = ['libs']
    }
  }
  packagingOptions {
    // 防止许可证违规（或多或少）：
    // 排除不必要的元数据：
    resources {
      pickFirsts += ['**/*' , 'META-INF/LICENSE.txt' , 'META-INF/LICENSE' , 'META-INF/license.txt' , 'META-INF/LGPL2.1' , 'META-INF/NOTICE.txt' , 'META-INF/NOTICE' , 'META-INF/notice.txt']
      excludes += ['META-INF/robovm/ios/robovm.xml' , 'META-INF/DEPENDENCIES.txt' , 'META-INF/DEPENDENCIES' , 'META-INF/dependencies.txt']
    }
    // exclude 'assets/image/src/*'
  }
  defaultConfig {
    compileSdk project.properties.compileSdkVersion.toInteger()
    applicationId 'pama1234.gdx.game.app.game0001.android'
    minSdkVersion project.properties.minSdkVersion.toInteger()
    targetSdkVersion project.properties.targetSdkVersion.toInteger()
    versionCode 1
    versionName "1.0"
    multiDexEnabled true
  }
  compileOptions {
    encoding = 'UTF-8'
    sourceCompatibility "21"
    targetCompatibility "21"
    coreLibraryDesugaringEnabled true
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt') , 'proguard-rules.pro'

      signingConfig signingConfigs.release
    }
  }

  buildFeatures {
    compose true
  }

  composeOptions {
    kotlinCompilerExtensionVersion = "1.4.0"
  }
}

Properties props = new Properties()
def propFile = rootProject.file('/doc/signing/signing.properties')
if(propFile.canRead()) {
  props.load(new FileInputStream(propFile))

  if(props != null && props.containsKey('STORE_FILE') && props.containsKey('STORE_PASSWORD') &&
      props.containsKey('KEY_ALIAS') && props.containsKey('KEY_PASSWORD')) {

    android.signingConfigs.release.storeFile = file(props['STORE_FILE'])
    android.signingConfigs.release.storePassword = props['STORE_PASSWORD']
    android.signingConfigs.release.keyAlias = props['KEY_ALIAS']
    android.signingConfigs.release.keyPassword = props['KEY_PASSWORD']
  } else {
    android.buildTypes.release.signingConfig = null
  }
} else {
  android.buildTypes.release.signingConfig = null
}

repositories {
  // 需要AAPT2，可能需要其他工具
  mavenCentral()
  maven { url 'https://jitpack.io' }
  google()
}

configurations { natives }

dependencies {
  coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:$androidDesugarVersion"

  implementation("$gdxModule:gdx-backend-android:$gdxVersion")

  implementation "com.github.simplepeng.SpiderMan:spiderman:$spidermanVersion"//如果程序异常闪退提供log

  implementation "$pama1234RepoLocation:server-framework:$pama1234PublishVersion"
  implementation("$pama1234RepoLocation:framework:$pama1234PublishVersion")
  implementation("$pama1234RepoLocation:android-framework:$pama1234PublishVersion")

  implementation(project(':game0001:game0001-core'))

  natives "$gdxModule:gdx-platform:$gdxVersion:natives-arm64-v8a"
  natives "$gdxModule:gdx-platform:$gdxVersion:natives-armeabi-v7a"
  natives "$gdxModule:gdx-platform:$gdxVersion:natives-x86"
  natives "$gdxModule:gdx-platform:$gdxVersion:natives-x86_64"

  // Compose UI dependencies for Android
  implementation("androidx.compose.ui:ui:$androidxComposeVersion")
  implementation("androidx.compose.material:material:$androidxComposeVersion")
  implementation("androidx.compose.ui:ui-tooling-preview:$androidxComposeVersion")
  implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.5")

  implementation("io.github.Rosemoe.sora-editor:editor:0.23.4")
}

// 每次gradle执行时调用，获取natives配置的本地依赖项，
// 并将它们提取到适当的libs/文件夹中，以便它们与APK一起打包。
task copyAndroidNatives() {
  doFirst {
    file("libs/armeabi-v7a/").mkdirs()
    file("libs/arm64-v8a/").mkdirs()
    file("libs/x86_64/").mkdirs()
    file("libs/x86/").mkdirs()

    configurations.getByName("natives").copy().files.each { jar ->
      def outputDir = null
      if(jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
      if(jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
      if(jar.name.endsWith("natives-x86_64.jar")) outputDir = file("libs/x86_64")
      if(jar.name.endsWith("natives-x86.jar")) outputDir = file("libs/x86")
      if(outputDir != null) {
        copy {
          from zipTree(jar)
          into outputDir
          include "*.so"
        }
      }
    }
  }
}

tasks.whenTaskAdded { packageTask ->
  if(packageTask.name.contains("package")) {
    packageTask.dependsOn 'copyAndroidNatives'
  }
}

task run(type: Exec) {
  def path
  def localProperties = project.file("../local.properties")
  if(localProperties.exists()) {
    Properties properties = new Properties()
    localProperties.withInputStream { instr ->
      properties.load(instr)
    }
    def sdkDir = properties.getProperty('sdk.dir')
    if(sdkDir) {
      path = sdkDir
    } else {
      path = "$System.env.ANDROID_SDK_ROOT"
    }
  } else {
    path = "$System.env.ANDROID_SDK_ROOT"
  }

  def adb = path + "/platform-tools/adb"
  commandLine "$adb" , 'shell' , 'am' , 'start' , '-n' , 'pama1234.gdx.game.app/pama1234.gdx.game.app.android.AndroidLauncher'
}

eclipse.project.name = appName + '0001-android'